# Generated by Django 2.1.3 on 2018-11-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=50)),
                ('grad_date', models.DateField(verbose_name='graduation date')),
            ],
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('join_date', models.DateField(verbose_name='join date')),
                ('profession', models.CharField(max_length=50)),
                ('inv_usd', models.FloatField()),
                ('inv_zco', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
